# .github/workflows/ci.yml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7
        options: --privileged

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.13.2

    - name: Install dependencies (backend)
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # You could run tests here if you have a tests suite
    #- name: Run tests
    #  working-directory: ./backend
    #  run: pytest

    - name: Lint code (backend)
      working-directory: ./backend
      run: |
        pip install flake8
        flake8 .

    - name: Build Docker images
      run: |
        docker build -t medcomp-backend ./backend
        docker build -t medcomp-frontend ./frontend

    # Optional: push built images to a container registry if needed.
